export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PRODUCT_LOADED = "PRODUCT_LOADED";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const LOAD_PRODUCT = "LOAD_PRODUCT";

// search
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';


// for filters
export const TOGGLE_BRAND = "TOGGLE_BRAND";
export const TOGGLE_STOCK = "TOGGLE_STOCK";